import Navigation from "../components/navigation"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// layout 컴포넌트를 렌더링 한 다음에 URL 확인 -> URL에 해당하는 컴포넌트를 불러옴
/*
 /about-us 페이지라면
 <Layout>
  <AboutUs>
 </Layout>
*/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navigation/>
        {children}
      </body>
    </html>
  )
}
