// metadata는 병합된다 (레이아웃과는 다른 개념)
// metadata는 페이지와 레이아웃을 통해서만 내보낼 수 있음

export const metadata = {
    description: 'Generated by Next.js',
}

export default function AboutUsLayout({
    children,
}: {
    children: React.ReactNode
})  {
    return (
        <div>
            {children}
            &copy; Next JS is great!
        </div>
    )
}